<?php


// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, "https://api.sandbox.paypal.com/v1/payments/payouts/1527668676?fields=batch_header");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");


$headers = array();
$headers[] = "Content-Type: application/json";
$headers[] = "Authorization: Bearer A21AAE0RnG1k9smzd7pwLU9mVO6dJx47eYLX7g_oaNgGmLQGGBoF4KAV5IUnvf2DQp27wyLJbo-5gnwyf72NOSvAGZ4EM2ujA";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);

if (curl_errno($ch)) 
{
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);

echo "<pre>";  print_r( json_decode( $result  ) );